### PR TITLE
nss-firmware & qca-nss-macsec: fix ipq6018 support

### LINKED ISSUE #29: Cannot select subtarget other than ipq807x
https://github.com/qosmio/nss-packages/blob/5fa030cfed30fdfec32f681c345fbf47d15d0fd3/firmware/nss-firmware/Makefile#L102

@qosmio After debugging, the problem is in this line, but I'm not very familiar with Makefile, so I don't know how to fix it.

### PR DESCRIPTION
**Pull request by JiaY-shi**
Fix: https://github.com/qosmio/nss-packages/issues/29

### CODE REVIEW

**Comment by qosmio** [comment]
Thanks for the PR! I'll take a look at getting this merged later this weekend when I can do a full build.

**Comment by qosmio** [comment]
Could you describe the primary problem you're having on IPQ6018? Does the package fail to build, or fail to load?

If it fails to load, the issue could be related to `/etc/hotplug.d/firmware/10-qca-nss-fw`

**Comment by JiaY-shi** [comment]
> Could you describe the primary problem you're having on IPQ6018? Does the package fail to build, or fail to load?
> 
> If it fails to load, the issue could be related to `/etc/hotplug.d/firmware/10-qca-nss-fw`

When compiling firmware, even if the subtarget of ipq6018 is selected, the nss firmware compiled into the firmware is still ipq807x. This is because the `eval` command only executes once, and selecting the IPQ_PLATFORM variable defined for the first time is ipq8074.

**Comment by qosmio** [comment]
Got it now. I went ahead and dropped $(NSS_ARCHIVE). Can you test to see if you still have an issue?

Updated PR with changes
[nss-firmware: fix building for IPQ60XX/IPQ50XX](174edae00a4efef4e4930fa6433a0ce5e8286472)

Committed as is:
[qca-nss-macsec: add ipq6018 support](1d044076d9853dd51ab5c8806d99de476ec4fe4d)

Thank you!

**Comment by JiaY-shi** [comment]
> Got it now. I went ahead and dropped $(NSS_ARCHIVE). Can you test to see if you still have an issue?
> 
> Updated PR with changes [nss-firmware: fix building for IPQ60XX/IPQ50XX](174edae00a4efef4e4930fa6433a0ce5e8286472)
> 
> Committed as is: [qca-nss-macsec: add ipq6018 support](1d044076d9853dd51ab5c8806d99de476ec4fe4d)
> 
> Thank you!

@qosmio After testing, it works fine, Thank you.

**Pull request closed without merging**
